on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: myazcr2022.azurecr.io
        username: ${{ secrets.acr_myazcr2022_username }}
        password: ${{ secrets.acr_myazcr2022_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/AcrHelloworld" -f  "AcrHelloworld/Dockerfile" -t myazcr2022.azurecr.io/aks:${{ github.sha }} --label dockerfile-path=AcrHelloworld/Dockerfile
        docker push myazcr2022.azurecr.io/aks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aks9eda | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aks9eda`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aks9eda
        container-registry-url: myazcr2022.azurecr.io
        container-registry-username: ${{ secrets.acr_myazcr2022_username }}
        container-registry-password: ${{ secrets.acr_myazcr2022_password }}
        secret-name: aksdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aks9eda
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          myazcr2022.azurecr.io/aks:${{ github.sha }}
        imagepullsecrets: |
          aksdockerauth
